const {
  SlashCommandBuilder,
  EmbedBuilder,
  PermissionFlagsBits,
} = require("discord.js");

module.exports = {
  data: new SlashCommandBuilder()
    .setName("servers")
    .setDescription("View all servers the bot is in, or generate an invite (owner-only)")
    .addStringOption(option =>
      option
        .setName("server_id")
        .setDescription("Optional: Server ID to generate an invite for")
        .setRequired(false)
    ),

  async execute(interaction) {
    const ownerId = ["424568410765262848",
                    "644600955295498249",
                    "386109687692656640",
                  "729614323978207323" ]; // 🔒 Replace with your Discord ID
    if (interaction.user.id !== ownerId)
      return interaction.reply({
        content: "🚫 This command is only available to the bot owner.",
        ephemeral: true,
      });

    const serverId = interaction.options.getString("server_id");

    // ----------- GENERATE INVITE FOR SPECIFIC SERVER -----------
    if (serverId) {
      const guild = interaction.client.guilds.cache.get(serverId);
      if (!guild)
        return interaction.reply({
          content: "⚠️ I’m not in that server or the ID is invalid.",
          ephemeral: true,
        });

      try {
        // Find a text channel where the bot has permission to create invites
        const channel =
          guild.channels.cache.find(
            ch =>
              ch.isTextBased() &&
              ch.permissionsFor(guild.members.me).has(PermissionFlagsBits.CreateInstantInvite)
          ) || null;

        if (!channel)
          return interaction.reply({
            content: "❌ I couldn’t find any channel where I can create an invite.",
            ephemeral: true,
          });

        const invite = await channel.createInvite({
          maxAge: 3600, // 1 hour
          maxUses: 1,
          reason: `Server invite generated by owner ${interaction.user.tag}`,
        });

        const embed = new EmbedBuilder()
          .setTitle("🎟️ Server Invite Generated")
          .addFields(
            { name: "Server", value: `${guild.name} (${guild.id})` },
            { name: "Invite Link", value: invite.url }
          )
          .setColor(0x57f287)
          .setTimestamp();

        return interaction.reply({ embeds: [embed], ephemeral: true });
      } catch (err) {
        console.error("❌ Error generating invite:", err);
        return interaction.reply({
          content: "❌ Failed to create an invite. Check my permissions.",
          ephemeral: true,
        });
      }
    }

    // ----------- LIST ALL SERVERS -----------
    const guilds = interaction.client.guilds.cache.map(guild => ({
      name: guild.name,
      id: guild.id,
      members: guild.memberCount,
    }));

    const embed = new EmbedBuilder()
      .setTitle("🌐 Servers I'm In")
      .setColor(0x5865f2)
      .setDescription(
        guilds
          .map(
            (g, i) =>
              `**${i + 1}.** ${g.name}\n🆔 ${g.id}\n👥 Members: ${g.members}`
          )
          .join("\n\n")
          .slice(0, 4000)
      )
      .setFooter({ text: `Total Servers: ${guilds.length}` })
      .setTimestamp();

    await interaction.reply({ embeds: [embed], ephemeral: true });
  },
};
